apiVersion: v1
kind: Secret
metadata:
  name: argocd-git-creds
  namespace: argocd
type: Opaque
data:
  username: Ym40Ng==
  password: Z2l0aHViX3BhdF8xMUJEQ0M2M0EwdDRTSXoyUkx6aXNvX2lzWUlyY3FrSEVqQTg1bjZaQzJrT0k4Z1FLRk5wd2ZBc3JoVE5zZDRlV2lIVFNYM1ROVzhNaVpxN1hB
