apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  namespace: argocd
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS0xLmRvY2tlci5pbyI6eyJ1c2VybmFtZSI6ImJuMTk5NyIsInBhc3N3b3JkIjoiQmh1bWk0MjdAQCIsImVtYWlsIjoiYmh1bWkxMTExMWFAZ21haWwuY29tIn19fQ==
