apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactoryservers 
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=docker.io/bn1997/artifactory-server:main    #Write repository name
    argocd-image-updater.argoproj.io/myalias.update-strategy: digest #There are several ways to update the image, but I'm using digest.
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: helm-details
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    
  labels:
    name: artifactoryserver
spec:
  project: default

  source:
    repoURL: git@github.com:bn46/mosip-helm.git
    targetRevision: develop
    path: charts/artifactory # path of the kubernetes application code means where you stored deployment.yaml, service.yaml etc
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc  # if you want to deploy application in the same cluster where argocd server is running if thats diffrent then use cluster IP address.
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
