apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
data:
  # Configuration for Docker Hub:
  registries.conf: |
    registries:
      - name: Docker Hub
        prefix: docker.io
        # No token needed for public Docker Hub
  polling-interval: 1m  # Check for updates every 3 minutes

