apiVersion: v1
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: Docker Hub
      api_url: https://registry-1.docker.io
      credentials: pullsecret:argocd/dockerhub-credentials  # Assuming a pull secret named "argocd/dockerhub-credentials" exists
      ping: yes
      prefix: docker.io
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
  namespace: argocd
